# Fichier Unique : policy-disallow-latest-tag.yaml

# --- PARTIE 1 : Le Modèle (La "Recette") ---
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdisallowlatesttag
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowLatestTag
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisallowlatesttag

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          endswith(container.image, ":latest")
          msg := sprintf("Image <%v> uses the 'latest' tag in container <%v>, which is not allowed", [container.image, container.name])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.initContainers[_]
          endswith(container.image, ":latest")
          msg := sprintf("Image <%v> uses the 'latest' tag in initContainer <%v>, which is not allowed", [container.image, container.name])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.ephemeralContainers[_]
          endswith(container.image, ":latest")
          msg := sprintf("Image <%v> uses the 'latest' tag in ephemeralContainer <%v>, which is not allowed", [container.image, container.name])
        }

--- # <--- SÉPARATEUR TRÈS IMPORTANT

# --- PARTIE 2 : La Contrainte (L'Application de la "Loi") ---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowLatestTag
metadata:
  name: no-latest-tags
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]